-- Online Library System

-- Users Table
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    membership_number VARCHAR2(20) UNIQUE,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    password VARCHAR2(100) NOT NULL,
    role VARCHAR2(20) DEFAULT 'MEMBER'
        CHECK (role IN ('MEMBER','ADMIN'))
);

-- Books Table
CREATE TABLE books (
    book_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(150) NOT NULL,
    author VARCHAR2(100),
    category VARCHAR2(50),
    available_copies NUMBER DEFAULT 1
);

